const SUPABASE_URL='https://ihcpuytxrgmercbvblfy.supabase.co';
const SUPABASE_KEY='sb_publishable_ILKwhlgiUJbBKtf4lMVZzA_u6RjjP79';
const sb=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
let user=null,currentPage='dashboard';
let theme=localStorage.getItem('ma_theme')||'dark';
let state={homes:[],cars:[],entries:[],definitions:[],documents:[]};
const $=id=>document.getElementById(id);
const fmt=n=>(Number(n)||0).toLocaleString('tr-TR')+' TL';
const today=()=>new Date().toISOString().slice(0,10);
const esc=s=>(s??'').toString().replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const DEFAULTS={home_expense:['DASK','Konut Sigortası','Emlak Vergisi','Gelir Vergisi','Aidat','Bakım','Onarım','Diğer'],car_expense:['MTV','Trafik Sigortası','Kasko','Muayene / Vize','Periyodik Bakım','Lastik','Yakıt','Ceza','Diğer'],income:['Kira','Depozito','Satış Geliri','Diğer Gelir'],status:['Bekleniyor','Ödendi','Alındı','Kısmi Ödendi','Gecikti','İptal'],doc_type:['Tapu','DASK','Kira Sözleşmesi','Ruhsat','Sigorta','Kasko','Fatura','Diğer']};
function toast(t){const d=document.createElement('div');d.className='toast';d.textContent=t;$('toast').appendChild(d);setTimeout(()=>d.remove(),3500)}
function openModal(html){$('modalbody').innerHTML=html;$('modal').classList.remove('hidden')}function closeModal(){$('modal').classList.add('hidden')}
$('close').onclick=closeModal;
async function init(){const {data}=await sb.auth.getSession();user=data.session?.user||null;renderAuth();if(user) await load();}
function renderAuth(){$('auth').classList.toggle('hidden',!!user);$('app').classList.toggle('hidden',!user);$('side').style.display=user?'block':'none';if(user) page(currentPage||'dashboard')}
async function load(){const [h,c,e,d,doc]=await Promise.all([sb.from('homes').select('*').order('created_at'),sb.from('cars').select('*').order('created_at'),sb.from('entries').select('*').order('date',{ascending:false}),sb.from('definitions').select('*').order('sort_order').order('name'),sb.from('documents').select('*').order('created_at',{ascending:false})]);if(h.error||c.error||e.error||d.error){toast('Supabase SQL eksik olabilir. V5 SQL kodunu çalıştır.');return}state.homes=h.data||[];state.cars=c.data||[];state.entries=e.data||[];state.definitions=d.data||[];state.documents=doc.data||[];await ensureDefaults();page(currentPage||'dashboard')}
async function ensureDefaults(){const need=[];Object.entries(DEFAULTS).forEach(([type,names])=>{if(!state.definitions.some(d=>d.type===type))names.forEach((name,i)=>need.push({user_id:user.id,type,name,sort_order:i,active:true}))});if(need.length){await sb.from('definitions').insert(need);const {data}=await sb.from('definitions').select('*').order('sort_order').order('name');state.definitions=data||[]}}
function defs(type,activeOnly=true){return state.definitions.filter(d=>d.type===type&&(!activeOnly||d.active))}
function optionHtml(type,selected=''){let arr=defs(type);if(!arr.length)arr=(DEFAULTS[type]||[]).map(name=>({name}));const val=selected||arr[0]?.name||'Diğer';return arr.map(o=>`<option value="${esc(o.name)}" ${o.name===val?'selected':''}>${esc(o.name)}</option>`).join('')}
function statusClass(s){return ['Ödendi','Alındı'].includes(s)?'ok':(s==='Gecikti'?'bad':'warn')}
function page(p){currentPage=p;document.querySelectorAll('.nav[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page==p));$('title').textContent={dashboard:'Dashboard',homes:'Gayrimenkuller',cars:'Araçlar',calendar:'Takvim',documents:'Belgeler',reports:'Raporlar',definitions:'Tanımlar',backup:'Yedek'}[p]||p;({dashboard,homes,cars,calendar,documents,reports,definitions,backup}[p])();$('side').classList.remove('open')}
function sum(arr,type){return arr.filter(e=>e.type===type).reduce((s,e)=>s+Number(e.amount||0),0)}
function assetValue(){return state.homes.reduce((s,h)=>s+Number(h.current_value||0),0)+state.cars.reduce((s,c)=>s+Number(c.current_value||0),0)}
function assetValueBreakdown(){return {home:state.homes.reduce((s,h)=>s+Number(h.current_value||0),0),car:state.cars.reduce((s,c)=>s+Number(c.current_value||0),0)}}
function dashboard(){const y=new Date().getFullYear(),m=new Date().getMonth();const month=state.entries.filter(e=>new Date(e.date).getMonth()==m&&new Date(e.date).getFullYear()==y);const income=sum(month,'income'),exp=sum(month,'expense');const yin=sum(state.entries.filter(e=>new Date(e.date).getFullYear()==y),'income');const yex=sum(state.entries.filter(e=>new Date(e.date).getFullYear()==y),'expense');const upcoming=getUpcoming();const docs=state.documents.length;const values=assetValueBreakdown();$('content').innerHTML=`<div class="hero"><span class="muted">Momentum Asset</span><b>${fmt(assetValue())}</b><span class="muted">Net varlık: Ev ${fmt(values.home)} + Araç ${fmt(values.car)}</span></div><div class="grid"><div class="kpi"><span>Bu Ay Gelir</span><b>${fmt(income)}</b></div><div class="kpi"><span>Bu Ay Gider</span><b>${fmt(exp)}</b></div><div class="kpi"><span>Bu Ay Net</span><b>${fmt(income-exp)}</b></div><div class="kpi"><span>Yaklaşan</span><b>${upcoming.length} kayıt</b></div></div><div class="grid"><div class="kpi"><span>Ev</span><b>${state.homes.length}</b></div><div class="kpi"><span>Araç</span><b>${state.cars.length}</b></div><div class="kpi"><span>Belge</span><b>${docs}</b></div><div class="kpi"><span>Yıllık Net</span><b>${fmt(yin-yex)}</b></div></div><div class="grid3"><div class="card"><h2>Önümüzdeki 30 Gün</h2>${calendarTimeline(upcoming, true)}</div><div class="card"><h2>Finans Asistanı</h2>${assistantTips(income,exp,yin,yex,upcoming)}</div></div><div class="grid2"><div class="card"><h2>En Çok Gider Kategorileri</h2>${topExpenseBars()}</div><div class="card"><h2>Son Hareketler</h2>${state.entries.slice(0,6).map(e=>entryCard(e,false)).join('')||'<p class="muted">Henüz kayıt yok.</p>'}</div></div><div class="grid2"><div class="card"><h2>Evler</h2>${state.homes.map(h=>assetLine('home',h)).join('')||'<p class="muted">Henüz ev yok.</p>'}</div><div class="card"><h2>Araçlar</h2>${state.cars.map(c=>assetLine('car',c)).join('')||'<p class="muted">Henüz araç yok.</p>'}</div></div>`}
function assistantTips(income,exp,yin,yex,upcoming){const tips=[];tips.push(`Bu ay net nakit akışın <b>${fmt(income-exp)}</b>.`);if(upcoming.length)tips.push(`${upcoming.length} adet yaklaşan ödeme/tahsilat var.`);const overdue=state.entries.filter(e=>!['Ödendi','Alındı','İptal'].includes(e.status)&&new Date(e.date)<new Date(today()));if(overdue.length)tips.push(`${overdue.length} kayıt gecikmiş görünüyor.`);tips.push(`Bu yıl toplam net durum <b>${fmt(yin-yex)}</b>.`);return tips.map(t=>`<div class="item">${t}</div>`).join('')}
function topExpenseBars(){const rows=group(state.entries.filter(e=>e.type==='expense'),'category');const max=Math.max(...rows.map(r=>r.total),1);return rows.slice(0,6).map(r=>`<div><div class="row"><b style="flex:1">${esc(r.key)}</b><span>${fmt(r.total)}</span></div><div class="bar"><i style="width:${Math.round(r.total/max*100)}%"></i></div></div>`).join('')||'<p class="muted">Gider kaydı yok.</p>'}
function assetLine(kind,a){const ent=state.entries.filter(e=>kind=='home'?e.home_id==a.id:e.car_id==a.id);const inc=sum(ent,'income'),ex=sum(ent,'expense');return `<div class="item"><h3>${esc(a.name)}</h3><span class="muted">Değer: ${fmt(a.current_value)} | Gelir: ${fmt(inc)} | Gider: ${fmt(ex)} | Net: ${fmt(inc-ex)}</span></div>`}
function homes(){$('content').innerHTML=`<div class="card"><div class="row"><h2 style="flex:1">Gayrimenkuller</h2><button onclick="homeForm()">Ev Ekle</button></div></div><div class="list">${state.homes.map(h=>assetCard('home',h)).join('')||'<div class="card muted">Ev ekleyerek başlayın.</div>'}</div>`}
function cars(){$('content').innerHTML=`<div class="card"><div class="row"><h2 style="flex:1">Araçlar</h2><button onclick="carForm()">Araç Ekle</button></div></div><div class="list">${state.cars.map(c=>assetCard('car',c)).join('')||'<div class="card muted">Araç ekleyerek başlayın.</div>'}</div>`}
function assetCard(kind,a){const ent=state.entries.filter(e=>kind=='home'?e.home_id==a.id:e.car_id==a.id);return `<div class="item"><h3>${esc(a.name)} ${kind==='home'?`<span class="badge">${esc(a.kind)}</span>`:`<span class="badge">${esc(a.plate||'')}</span>`}</h3><p class="muted">${esc(a.address||a.note||'')}</p><p>Güncel Değer: <b>${fmt(a.current_value)}</b> | Gelir: <b>${fmt(sum(ent,'income'))}</b> | Gider: <b>${fmt(sum(ent,'expense'))}</b></p><div class="row">${kind==='home'?`<button onclick="entryForm('home','${a.id}','income')">Gelir Ekle</button>`:''}<button onclick="entryForm('${kind}','${a.id}','expense')">Gider Ekle</button><button class="secondary" onclick="showAssetEntries('${kind}','${a.id}')">Kayıtlar</button><button class="secondary" onclick="showDocs('${kind}','${a.id}')">Belgeler</button><button class="secondary" onclick="${kind}Form('${a.id}')">Düzenle</button><button class="danger" onclick="delAsset('${kind==='home'?'homes':'cars'}','${a.id}')">Sil</button></div></div>`}
function showAssetEntries(kind,id){const asset=(kind==='home'?state.homes:state.cars).find(x=>x.id===id);const all=state.entries.filter(e=>kind==='home'?e.home_id===id:e.car_id===id);openModal(`<h2>${esc(asset?.name||'Kayıtlar')}</h2><div class="split"><div><h3>Gelirler</h3>${entryTable(all.filter(e=>e.type==='income'))}</div><div><h3>Giderler</h3>${entryTable(all.filter(e=>e.type==='expense'))}</div></div>`)}
function entryDocs(entryId){return state.documents.filter(d=>d.entry_id===entryId)}
function entryLabel(e){return `${e.type==='income'?'Gelir':'Gider'} / ${e.category||'Diğer'} / ${fmt(e.amount)} / ${e.date}`}
function entryTable(list){return list.length?`<div class="tablewrap"><table class="table"><thead><tr><th>Tarih</th><th>Kategori</th><th>Tutar</th><th>Durum</th><th>Belge</th><th>Açıklama</th><th>İşlem</th></tr></thead><tbody>${list.map(e=>{const dc=entryDocs(e.id).length;return `<tr><td data-label="Tarih">${esc(e.date)}</td><td data-label="Kategori">${esc(e.category||'Diğer')}</td><td data-label="Tutar">${fmt(e.amount)}</td><td data-label="Durum"><span class="badge ${statusClass(e.status)}">${esc(e.status)}</span></td><td data-label="Belge">${dc?`📎 ${dc}`:'-'}</td><td data-label="Açıklama">${esc(e.note||'')}</td><td data-label="İşlem"><button class="small secondary" onclick="entryForm('${e.home_id?'home':'car'}','${e.home_id||e.car_id}','${e.type}','${e.id}')">Düzenle</button> <button class="small secondary" onclick="showDocs('${e.home_id?'home':'car'}','${e.home_id||e.car_id}','${e.id}')">Belge</button> <button class="small danger" onclick="delEntry('${e.id}')">Sil</button></td></tr>`}).join('')}</tbody></table></div>`:'<p class="muted">Kayıt yok.</p>'}
function calendar(){const upcoming=getUpcoming(365);$('content').innerHTML=`<div class="card"><div class="row"><h2 style="flex:1">Finans Takvimi</h2><button class="secondary" onclick="quickAction()">+ Hızlı İşlem</button></div>${calendarTimeline(upcoming,false)}</div>`}
function calendarTimeline(list,compact=false){if(!list.length)return '<div class="empty">Açık veya yaklaşan kayıt yok.</div>';const groups={};list.forEach(e=>{groups[e.date]??=[];groups[e.date].push(e)});return `<div class="timeline">${Object.keys(groups).sort().map(d=>`<div class="day"><h3>${trDate(d)}</h3>${groups[d].map(e=>entryCard(e,!compact)).join('')}</div>`).join('')}</div>`}
function trDate(d){return new Date(d+'T00:00:00').toLocaleDateString('tr-TR',{day:'2-digit',month:'long',year:'numeric',weekday:'long'})}
function reports(){const homeEntries=state.entries.filter(e=>e.home_id),carEntries=state.entries.filter(e=>e.car_id);$('content').innerHTML=`<div class="grid"><div class="kpi">Ev Değeri<b>${fmt(state.homes.reduce((s,h)=>s+Number(h.current_value||0),0))}</b></div><div class="kpi">Araç Değeri<b>${fmt(state.cars.reduce((s,c)=>s+Number(c.current_value||0),0))}</b></div><div class="kpi">Ev Net<b>${fmt(sum(homeEntries,'income')-sum(homeEntries,'expense'))}</b></div><div class="kpi">Araç Maliyeti<b>${fmt(sum(carEntries,'expense'))}</b></div></div><div class="grid2"><div class="card"><h2>Ev Alt Kategori Raporu</h2>${reportTable(homeEntries)}</div><div class="card"><h2>Araç Alt Kategori Raporu</h2>${reportTable(carEntries)}</div></div><div class="card"><h2>Varlık Değerleri</h2>${assetValueTable()}</div>`}
function reportTable(arr){const rows=group(arr,'category');return rows.length?`<table class="table"><thead><tr><th>Kategori</th><th>Gelir</th><th>Gider</th><th>Net</th></tr></thead><tbody>${rows.map(r=>`<tr><td data-label="Kategori">${esc(r.key)}</td><td data-label="Gelir">${fmt(r.income)}</td><td data-label="Gider">${fmt(r.expense)}</td><td data-label="Net">${fmt(r.income-r.expense)}</td></tr>`).join('')}</tbody></table>`:'<p class="muted">Kayıt yok.</p>'}
function assetValueTable(){const rows=[...state.homes.map(x=>({t:'Ev',...x})),...state.cars.map(x=>({t:'Araç',...x}))];return rows.length?`<table class="table"><thead><tr><th>Tip</th><th>Ad</th><th>Alış Fiyatı</th><th>Güncel Değer</th><th>Fark</th></tr></thead><tbody>${rows.map(r=>`<tr><td data-label="Tip">${r.t}</td><td data-label="Ad">${esc(r.name)}</td><td data-label="Alış">${fmt(r.purchase_price)}</td><td data-label="Güncel">${fmt(r.current_value)}</td><td data-label="Fark">${fmt(Number(r.current_value||0)-Number(r.purchase_price||0))}</td></tr>`).join('')}</tbody></table>`:'<p class="muted">Varlık yok.</p>'}
function group(arr,key){const m={};arr.forEach(e=>{const k=e[key]||'Diğer';m[k]??={key:k,income:0,expense:0,total:0};m[k][e.type]+=Number(e.amount||0);m[k].total+=Number(e.amount||0)});return Object.values(m).sort((a,b)=>b.total-a.total)}
function definitions(){const labels={home_expense:'Ev Gider Kategorileri',car_expense:'Araç Gider Kategorileri',income:'Gelir Tipleri',status:'Ödeme Durumları',doc_type:'Belge Tipleri'};$('content').innerHTML=`<div class="defgrid">${Object.keys(labels).map(type=>`<div class="card"><div class="row"><h2 style="flex:1">${labels[type]}</h2><button onclick="defForm('${type}')">Ekle</button></div>${defs(type,false).map(d=>`<div class="pill ${d.active?'':'inactive'}"><span>${esc(d.name)} ${d.active?'':'(pasif)'}</span><span><button class="small secondary" onclick="defForm('${type}','${d.id}')">Düzenle</button> <button class="small secondary" onclick="toggleDef('${d.id}',${!d.active})">${d.active?'Pasife Al':'Aktif Et'}</button> <button class="small danger" onclick="deleteDef('${d.id}')">Sil</button></span></div>`).join('')}</div>`).join('')}</div>`}
function documents(){const docs=state.documents;$('content').innerHTML=`<div class="card"><div class="row"><h2 style="flex:1">Belge Merkezi</h2><button class="secondary" onclick="quickDoc()">Belge Yükle</button></div><p class="muted">Tüm ev ve araç belgeleri tek ekranda.</p>${docs.map(d=>docRow(d)).join('')||'<div class="empty">Henüz belge yok.</div>'}</div>`}
function docRow(d){const asset=d.home_id?state.homes.find(h=>h.id===d.home_id):state.cars.find(c=>c.id===d.car_id);const e=state.entries.find(x=>x.id===d.entry_id);return `<div class="doc"><div><b>${esc(d.doc_type||'Belge')}</b><br><span>${esc(asset?.name||'Varlık yok')}</span><br><span class="muted">${esc(d.file_name)}${e?' — '+esc(entryLabel(e)):' — Genel belge'}</span></div><div><button class="small secondary" onclick="openDoc('${d.file_path}')">Aç</button> <button class="small danger" onclick="deleteDoc('${d.id}','${d.file_path}')">Sil</button></div></div>`}
function backup(){$('content').innerHTML=`<div class="card"><h2>Yedek</h2><p class="muted">Tüm verilerini JSON olarak indir.</p><button onclick="exportData()">Yedek İndir</button></div>`}
function homeForm(id){const h=state.homes.find(x=>x.id===id)||{};openModal(`<h2>${id?'Ev Düzenle':'Ev Ekle'}</h2><input id="f_name" placeholder="Ev adı" value="${esc(h.name)}"><select id="f_kind"><option ${h.kind==='Kiradaki Ev'?'selected':''}>Kiradaki Ev</option><option ${h.kind==='Oturulan Ev'?'selected':''}>Oturulan Ev</option></select><textarea id="f_address" placeholder="Adres / not">${esc(h.address)}</textarea><div class="split"><div><input id="f_purchase_price" type="number" placeholder="Alış fiyatı" value="${h.purchase_price||''}"></div><div><input id="f_current_value" type="number" placeholder="Güncel değer" value="${h.current_value||''}"></div></div><input id="f_purchase_date" type="date" value="${h.purchase_date||''}"><h3>Kiracı Bilgileri</h3><input id="f_tenant_name" placeholder="Kiracı adı" value="${esc(h.tenant_name)}"><input id="f_tenant_phone" placeholder="Kiracı telefon" value="${esc(h.tenant_phone)}"><div class="split"><input id="f_rent_amount" type="number" placeholder="Kira tutarı" value="${h.rent_amount||''}"><input id="f_rent_increase_month" placeholder="Kira artış ayı" value="${esc(h.rent_increase_month)}"></div><button onclick="saveHome('${id||''}')">Kaydet</button>`)}
async function saveHome(id){const row={user_id:user.id,name:$('f_name').value,kind:$('f_kind').value,address:$('f_address').value,purchase_price:$('f_purchase_price').value||0,current_value:$('f_current_value').value||0,purchase_date:$('f_purchase_date').value||null,tenant_name:$('f_tenant_name').value,tenant_phone:$('f_tenant_phone').value,rent_amount:$('f_rent_amount').value||0,rent_increase_month:$('f_rent_increase_month').value};const q=id?sb.from('homes').update(row).eq('id',id):sb.from('homes').insert(row);const {error}=await q;if(error)return toast(error.message);closeModal();await load()}
function carForm(id){const c=state.cars.find(x=>x.id===id)||{};openModal(`<h2>${id?'Araç Düzenle':'Araç Ekle'}</h2><input id="f_name" placeholder="Araç adı" value="${esc(c.name)}"><input id="f_plate" placeholder="Plaka" value="${esc(c.plate)}"><textarea id="f_note" placeholder="Not">${esc(c.note)}</textarea><div class="split"><input id="f_purchase_price" type="number" placeholder="Alış fiyatı" value="${c.purchase_price||''}"><input id="f_current_value" type="number" placeholder="Güncel değer" value="${c.current_value||''}"></div><div class="split"><input id="f_purchase_date" type="date" value="${c.purchase_date||''}"><input id="f_km" type="number" placeholder="Güncel km" value="${c.km||''}"></div><button onclick="saveCar('${id||''}')">Kaydet</button>`)}
async function saveCar(id){const row={user_id:user.id,name:$('f_name').value,plate:$('f_plate').value,note:$('f_note').value,purchase_price:$('f_purchase_price').value||0,current_value:$('f_current_value').value||0,purchase_date:$('f_purchase_date').value||null,km:$('f_km').value||0};const q=id?sb.from('cars').update(row).eq('id',id):sb.from('cars').insert(row);const {error}=await q;if(error)return toast(error.message);closeModal();await load()}
function entryForm(kind,assetId,type,id){const e=state.entries.find(x=>x.id===id)||{};const catType=type==='income'?'income':(kind==='home'?'home_expense':'car_expense');openModal(`<h2>${id?'Kayıt Düzenle':'Kayıt Ekle'}</h2><label>Kategori</label><select id="f_category">${optionHtml(catType,e.category)}</select><label>Tutar</label><input id="f_amount" type="number" value="${e.amount||''}"><label>Tarih</label><input id="f_date" type="date" value="${e.date||today()}"><label>Tekrar</label><select id="f_repeat"><option>Tek seferlik</option><option>Aylık</option><option>6 aylık</option><option>Yıllık</option></select><label>Durum</label><select id="f_status">${optionHtml('status',e.status)}</select><textarea id="f_note" placeholder="Açıklama">${esc(e.note)}</textarea><button onclick="saveEntry('${kind}','${assetId}','${type}','${id||''}')">Kaydet</button>`);$('f_repeat').value=e.repeat_type||'Tek seferlik'}
async function saveEntry(kind,assetId,type,id){const row={user_id:user.id,type,category:$('f_category').value||'Diğer',amount:$('f_amount').value||0,date:$('f_date').value,repeat_type:$('f_repeat').value,status:$('f_status').value,note:$('f_note').value,home_id:kind==='home'?assetId:null,car_id:kind==='car'?assetId:null};const q=id?sb.from('entries').update(row).eq('id',id):sb.from('entries').insert(row);const {error}=await q;if(error)return toast(error.message);closeModal();await load()}
function defForm(type,id){const d=state.definitions.find(x=>x.id===id)||{};openModal(`<h2>Tanım ${id?'Düzenle':'Ekle'}</h2><input id="f_name" placeholder="Ad" value="${esc(d.name)}"><input id="f_sort" type="number" placeholder="Sıra" value="${d.sort_order??0}"><button onclick="saveDef('${type}','${id||''}')">Kaydet</button>`)}
async function saveDef(type,id){const row={user_id:user.id,type,name:$('f_name').value,sort_order:Number($('f_sort').value)||0,active:true};const q=id?sb.from('definitions').update(row).eq('id',id):sb.from('definitions').insert(row);const {error}=await q;if(error)return toast(error.message);closeModal();await load()}
async function toggleDef(id,active){await sb.from('definitions').update({active}).eq('id',id);await load()}
async function deleteDef(id){const d=state.definitions.find(x=>x.id===id);const used=state.entries.some(e=>e.category===d?.name||e.status===d?.name)||state.documents.some(x=>x.doc_type===d?.name);if(used){toast('Bu tanım geçmiş kayıtlarda kullanılıyor. Pasife alındı.');await toggleDef(id,false);return}if(confirm('Tanım tamamen silinsin mi?')){await sb.from('definitions').delete().eq('id',id);await load()}}
function showDocs(kind,id,entryId=''){
  const asset=(kind==='home'?state.homes:state.cars).find(x=>x.id===id);
  const entries=state.entries.filter(e=>kind==='home'?e.home_id===id:e.car_id===id);
  const currentEntry=state.entries.find(e=>e.id===entryId);
  const docs=state.documents.filter(d=>(kind==='home'?d.home_id===id:d.car_id===id) && (!entryId || d.entry_id===entryId));
  const entryOptions=`<option value="">Genel belge / kayıt bağlantısı yok</option>`+entries.map(e=>`<option value="${e.id}" ${e.id===entryId?'selected':''}>${esc(entryLabel(e))}</option>`).join('');
  openModal(`<h2>Belgeler</h2><p class="muted">${esc(asset?.name||'Varlık')} ${currentEntry?`→ ${esc(entryLabel(currentEntry))}`:''}</p><div class="card"><label>Belge Tipi</label><select id="doc_type">${optionHtml('doc_type')}</select><label>İlgili Kayıt</label><select id="doc_entry_id">${entryOptions}</select><input id="doc_file" type="file"><button onclick="uploadDoc('${kind}','${id}')">Yükle</button><p class="muted">Belgeyi genel olarak ev/araca bağlayabilir veya belirli bir gelir/gider kaydıyla ilişkilendirebilirsin.</p></div>${docs.map(d=>{const e=state.entries.find(x=>x.id===d.entry_id);return `<div class="doc"><div><b>${esc(d.doc_type)}</b><br><span class="muted">${esc(d.file_name)}</span><br><span class="muted">${e?'Bağlı kayıt: '+esc(entryLabel(e)):'Genel belge'}</span></div><div><button class="small secondary" onclick="openDoc('${d.file_path}')">Aç</button> <button class="small danger" onclick="deleteDoc('${d.id}','${d.file_path}')">Sil</button></div></div>`}).join('')||'<p class="muted">Belge yok.</p>'}`)
}
function safeFileName(name){
  const parts=name.split('.');
  const ext=parts.length>1?'.'+parts.pop().toLowerCase().replace(/[^a-z0-9]/g,''):'';
  const base=parts.join('.')||'belge';
  return base
    .normalize('NFD').replace(/[\u0300-\u036f]/g,'')
    .replace(/ı/g,'i').replace(/İ/g,'I')
    .replace(/ğ/g,'g').replace(/Ğ/g,'G')
    .replace(/ü/g,'u').replace(/Ü/g,'U')
    .replace(/ş/g,'s').replace(/Ş/g,'S')
    .replace(/ö/g,'o').replace(/Ö/g,'O')
    .replace(/ç/g,'c').replace(/Ç/g,'C')
    .replace(/[^a-zA-Z0-9-_]/g,'-')
    .replace(/-+/g,'-')
    .replace(/^-|-$/g,'')
    .slice(0,80)+ext;
}
async function uploadDoc(kind,id){
  const f=$('doc_file').files[0];
  if(!f)return toast('Dosya seç.');
  const clean=safeFileName(f.name);
  const path=`${user.id}/${kind}/${id}/${Date.now()}-${clean}`;
  const up=await sb.storage.from('asset-documents').upload(path,f,{upsert:false,contentType:f.type||'application/octet-stream'});
  if(up.error)return toast(up.error.message);
  const entryId=$('doc_entry_id')?.value||null;
  const row={user_id:user.id,home_id:kind==='home'?id:null,car_id:kind==='car'?id:null,entry_id:entryId,doc_type:$('doc_type').value,file_name:f.name,file_path:path};
  const {error}=await sb.from('documents').insert(row);
  if(error){await sb.storage.from('asset-documents').remove([path]);return toast(error.message)}
  await load();showDocs(kind,id,entryId||'')
}
async function openDoc(path){const {data,error}=await sb.storage.from('asset-documents').createSignedUrl(path,120);if(error)return toast(error.message);window.open(data.signedUrl,'_blank')}
async function deleteDoc(id,path){if(!confirm('Belge silinsin mi?'))return;await sb.storage.from('asset-documents').remove([path]);await sb.from('documents').delete().eq('id',id);await load();closeModal()}
function entryCard(e,withActions=false){const asset=e.home_id?state.homes.find(h=>h.id===e.home_id)?.name:state.cars.find(c=>c.id===e.car_id)?.name;const dc=entryDocs(e.id).length;return `<div class="item"><div class="row"><b style="flex:1">${esc(asset||'Kayıt')} / ${esc(e.category||'Diğer')} ${dc?`📎 ${dc}`:''}</b><span class="badge ${statusClass(e.status)}">${esc(e.status)}</span></div><div>${fmt(e.amount)} - ${esc(e.date)} - ${esc(e.repeat_type||'')}</div><p class="muted">${esc(e.note||'')}</p>${withActions?`<div class="row"><button class="small secondary" onclick="entryForm('${e.home_id?'home':'car'}','${e.home_id||e.car_id}','${e.type}','${e.id}')">Düzenle</button><button class="small secondary" onclick="showDocs('${e.home_id?'home':'car'}','${e.home_id||e.car_id}','${e.id}')">Belge</button><button class="small danger" onclick="delEntry('${e.id}')">Sil</button></div>`:''}</div>`}
async function delEntry(id){if(confirm('Kayıt silinsin mi?')){await sb.from('entries').delete().eq('id',id);await load();closeModal()}}
async function delAsset(table,id){if(confirm('Bu varlık silinsin mi? İlgili gelir/gider kayıtları silinmez.')){await sb.from(table).delete().eq('id',id);await load()}}
function getUpcoming(days=30){const now=new Date(today());const max=new Date(now);max.setDate(max.getDate()+days);return state.entries.filter(e=>!['Ödendi','Alındı','İptal'].includes(e.status)&&new Date(e.date)>=now&&new Date(e.date)<=max).sort((a,b)=>a.date.localeCompare(b.date))}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='momentum-asset-v5-yedek.json';a.click()}
function quickAction(){openModal(`<h2>Hızlı İşlem</h2><div class="quickgrid"><button class="quicktile" onclick="homeForm()"><b>🏠 Yeni Ev</b><br><span class="muted">Gayrimenkul ekle</span></button><button class="quicktile" onclick="carForm()"><b>🚗 Yeni Araç</b><br><span class="muted">Araç ekle</span></button><button class="quicktile" onclick="quickEntry('income')"><b>💰 Gelir</b><br><span class="muted">Kira / diğer gelir</span></button><button class="quicktile" onclick="quickEntry('expense')"><b>💸 Gider</b><br><span class="muted">Ev veya araç gideri</span></button><button class="quicktile" onclick="quickDoc()"><b>📎 Belge</b><br><span class="muted">Dosya yükle</span></button><button class="quicktile" onclick="page('calendar');closeModal()"><b>📅 Takvim</b><br><span class="muted">Yaklaşanları gör</span></button></div>`)}
function quickEntry(type){const opts=[...state.homes.map(h=>`<option value="home:${h.id}">Ev: ${esc(h.name)}</option>`),...state.cars.map(c=>`<option value="car:${c.id}">Araç: ${esc(c.name)}</option>`)].join('');if(!opts)return toast('Önce ev veya araç ekle.');openModal(`<h2>${type==='income'?'Gelir':'Gider'} için varlık seç</h2><select id="quick_asset">${opts}</select><button onclick="const v=$('quick_asset').value.split(':'); entryForm(v[0],v[1],'${type}')">Devam</button>`)}
function quickDoc(){const opts=[...state.homes.map(h=>`<option value="home:${h.id}">Ev: ${esc(h.name)}</option>`),...state.cars.map(c=>`<option value="car:${c.id}">Araç: ${esc(c.name)}</option>`)].join('');if(!opts)return toast('Önce ev veya araç ekle.');openModal(`<h2>Belge için varlık seç</h2><select id="quick_asset">${opts}</select><button onclick="const v=$('quick_asset').value.split(':'); showDocs(v[0],v[1])">Devam</button>`)}
function doSearch(q){q=(q||'').toLowerCase().trim();if(!q)return page(currentPage);const rows=[];state.homes.forEach(h=>{if(JSON.stringify(h).toLowerCase().includes(q))rows.push(`<div class="item"><b>🏠 ${esc(h.name)}</b><p class="muted">${esc(h.address||'')}</p><button class="small secondary" onclick="page('homes')">Gayrimenkullere git</button></div>`)});state.cars.forEach(c=>{if(JSON.stringify(c).toLowerCase().includes(q))rows.push(`<div class="item"><b>🚗 ${esc(c.name)}</b><p class="muted">${esc(c.plate||'')}</p><button class="small secondary" onclick="page('cars')">Araçlara git</button></div>`)});state.entries.forEach(e=>{if(JSON.stringify(e).toLowerCase().includes(q))rows.push(entryCard(e,true))});state.documents.forEach(d=>{if(JSON.stringify(d).toLowerCase().includes(q))rows.push(docRow(d))});$('title').textContent='Arama';$('content').innerHTML=`<div class="card"><h2>Arama Sonuçları</h2><p class="muted">${esc(q)} için ${rows.length} sonuç</p><div class="searchResult">${rows.join('')||'<div class="empty">Sonuç bulunamadı.</div>'}</div></div>`}
function applyTheme(){document.body.classList.toggle('light',theme==='light')}
function toggleTheme(){theme=theme==='light'?'dark':'light';localStorage.setItem('ma_theme',theme);applyTheme()}
$('login').onclick=async()=>{const r=await sb.auth.signInWithPassword({email:$('email').value,password:$('pass').value});if(r.error)toast(r.error.message);else{user=r.data.user;await load();renderAuth()}};
$('signup').onclick=async()=>{const r=await sb.auth.signUp({email:$('email').value,password:$('pass').value});if(r.error)toast(r.error.message);else toast('Kayıt oluşturuldu. Mail onayı gerekiyorsa gelen kutunu kontrol et.')};
$('logout').onclick=async()=>{await sb.auth.signOut();user=null;renderAuth()};
document.querySelectorAll('.nav[data-page]').forEach(b=>b.onclick=()=>page(b.dataset.page));$('menu').onclick=()=>$('side').classList.toggle('open');
$('quick').onclick=quickAction;$('fab').onclick=quickAction;$('themeBtn').onclick=toggleTheme;applyTheme();
let searchTimer=null;$('globalSearch').addEventListener('input',e=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>doSearch(e.target.value),250)});
init();
